DROP TABLE SERVICO;
DROP TABLE HOSPEDE;
DROP TABLE QUARTO;
DROP TABLE RESERVA;
DROP TABLE REQUISITA;

CREATE TABLE SERVICO(
  CODIGO INT NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  VALOR NUMERIC(10, 2),
  PRIMARY KEY(CODIGO)
  );
  
  CREATE TABLE HOSPEDE(
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE,
    TELEFONE CHAR(14),
    PRIMARY KEY(CPF)
    );
    
    CREATE TABLE QUARTO(
      NUMERO INT NOT NULL,
      TIPO CHAR(1) NOT NULL,
      PRIMARY KEY(NUMERO)
      );
      
      CREATE TABLE RESERVA(
        RESERVA INT NOT NULL,
        CPF CHAR(18) NOT NULL,
        QUARTO INT NOT NULL,
        CHECKIN TIMESTAMP,
        CHECKOUT TIMESTAMP,
        VALOR_CONTA NUMERIC(10, 2),
        PRIMARY KEY(RESERVA),
        FOREIGN KEY(CPF) REFERENCES HOSPEDE(RESERVA),
        FOREIGN KEY(QUARTO) REFERENCES QUARTO(RESERVA)
        );
        
        CREATE TABLE REQUISITA(
          REQUISICAO INT NOT NULL,
          RESERVA INT NOT NULL,
          SERVICO INT NOT NULL,
          DATA_REQUISICAO DATE,
          PRIMARY KEY(REQUISICAO),
          FOREIGN KEY(RESERVA) REFERENCES RESERVA(RESERVA),
          FOREIGN KEY(SERVICO) REFERENCES SERVICO(SERVICO)
          );
