DROP TABLE CLIENTE;
DROP TABLE ITEM;
DROP TABLE LABORATORIO;
DROP TABLE MEDICAMENTO;
DROP TABLE PEDIDO;

CREATE TABLE CLIENTE(
  CNPJ CHAR(18) NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  ENDERECO VARCHAR(100),
  CIDADE VARCHAR(60),
  ESTADO CHAR(2),
  CEP CHAR(9) NOT NULL,
  TELEFONE CHAR(14),
  CONTATO VARCHAR(60),
  PRIMARY KEY (CNPJ)
  );
  
  CREATE TABLE PEDIDO(
    NUMERO INT NOT NULL,
    DATA_PEDIDO DATE NOT NULL,
    CNPJ CHAR(18) NOT NULL,
    VALOR_TOTAL NUMERIC(10, 2),
    PRIMARY KEY (NUMERO),
    FOREIGN KEY (NUMERO) REFERENCES CNPJ (NUMERO)
    );
    
    CREATE TABLE ITEM(
      ITEM INT NOT NULL,
      PEDIDO INT NOT NULL,
      MEDICAMENTO INT NOT NULL,
      QUANTIDADE INT NOT NULL,
      PRECO NUMERIC (10, 2),
      PRIMARY KEY (ITEM),
      FOREIGN KEY (ITEM) REFERENCES PEDIDO (ITEM),
      FOREIGN KEY (ITEM) REFERENCES MEDICAMENTO (ITEM)
      );
      
      CREATE TABLE MEDICAMENTO(
        CODIGO INT NOT NULL,
        TIPO CHAR(1) NOT NULL,
        DATA_VALIDADE DATE NOT NULL,
        NOME VARCHAR(100),
        PRINCIPIO_ATIVO VARCHAR(100),
        COR_TARJA VARCHAR(100),
        LABORATORIO INT NOT NULL,
        PRIMARY KEY (CODIGO),
        FOREIGN KEY (CODIGO) REFERENCES LABORATORIO (CODIGO)
        );
        
        CREATE TABLE LABORATORIO(
          CODIGO INT NOT NULL,
          NOME VARCHAR(100) NOT NULL,
          PRIMARY KEY (CODIGO)
          );
