DROP TABLE LABORATORIO;
DROP TABLE CLIENTE;
DROP TABLE PEDIDO;
DROP TABLE ITEM;
DROP TABLE MEDICAMENTO;

   CREATE TABLE LABORATORIO(
      CODIGO INT NOT NULL,
      NOME VARCHAR(100) NOT NULL,
      PRIMARY KEY(CODIGO)
  );
  
   CREATE TABLE CLIENTE(
     CNPJ CHAR(18) NOT NULL,
     NOME VARCHAR(100) NOT NULL,
     ENDEREÇO VARCHAR(100),
     CIDADE VARCHAR(30),
     ESTADO VARCHAR(2),
     CEP CHAR(9),
     TELEFONE CHAR(14),
     CONTATO VARCHAR(30),
     PRIMARY KEY(CNPJ)
      );
      
    CREATE TABLE PEDIDO(
      NUMERO INT NOT NULL,
      DATA_PEDIDO DATE NOT NULL,
      CNPJ CHAR(18) NOT NULL,
      VALOR_TOTAL NUMERIC(10, 2),
      PRIMARY KEY(NUMERO),
      FOREIGN KEY (CNPJ) REFERENCES CNPJ(PEDIDO)
        );   
      
     CREATE TABLE ITEM(
      ITEM INT NOT NULL,
      PEDIDO INT NOT NULL,
      MEDICAMENTO INT NOT NULL,
      QUANTIDADE INT NOT NULL,
      PRECO NUMERIC(10, 2),
      PRIMARY KEY(ITEM),
      FOREIGN KEY(PEDIDO) REFERENCES PEDIDO (PEDIDO),
      FOREIGN KEY(MEDICAMENTO) REFERENCES MEDICAMENTO (ITEM)
      );     
      
   CREATE TABLE MEDICAMENTO(
     CODIGO INT NOT NULL,
     TIPO VARCHAR(1) NOT NULL,
     DATA_VALIDADE DATE NOT NULL,
     NOME VARCHAR(100),
     PRINCIPIO_ATIVO VARCHAR(100),
     COR_TARJA VARCHAR(20),
     LABORATORIO INT NOT NULL,
     PRIMARY KEY(CODIGO),
     FOREIGN KEY(LABORATORIO) REFERENCES LABORATORIO (MEDICAMENTO)
    );
